<?php

  function westminster_colorful_preprocess_html(&$variables) {
    $variables['#attached']['library'][] = 'westminster_colorful/westminster_colorful';
  }

  function westminster_colorful_preprocess_page__admin__config__westminster__colorful(&$variables) {
    $variables['#attached']['library'][] = 'westminster_colorful/westminster_colorful_theme';
  }

  function westminster_colorful_install() {
    $filepath = drupal_get_path('module', 'westminster_colorful');
    file_put_contents($filepath.'/css/westminster-colorful.css', '');
  }

  function westminster_colorful_modules_installed() {
    drupal_flush_all_caches();
  }

  function westminster_colorful_uninstall() {
    $filepath = drupal_get_path('module', 'westminster_colorful');
    unlink($filepath.'/css/westminster-colorful.css');
  }

  function westminster_colorful_update_8001() {
    $configFactory = \Drupal::configFactory()->getEditable('westminster_colorful.configuration');
    $boxColors = [
      'background' => [
        'color' => '#ffffff',
      ],
      'text' => [
        'color' => '#333333',
      ],
      'link' => [
        'color' => '#3c8dbc',
      ],
      'link_hover' => [
        'color' => '#72afd2',
      ],
      'border' => [
        'color' => '#cccccc',
      ],
    ];
    $configFactory->set('box', $boxColors);
    $configFactory->set('vertical_tabs', $boxColors);
    $configFactory->save(TRUE);
  }
